title: jmfaerman
email: spam@jfaerman.com.br
description: Code Fast Die Last!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jmfaerman.com" # the base hostname & protocol for your site
twitter_username: jmfaerman
github_username:  jfaerman
markdown: kramdown
collections:
  talks:
      output: true
  workshops:
      output: true
